### ISSUE TITLE
Add Gain framework to list

### ISSUE THREAD

**Issue by pawelgaczynski** [espoal/awesome-iouring#11]
Hi @espoal . Please add my framework to the list. Gain is a high-performance io_uring networking framework written entirely in Go.

https://github.com/pawelgaczynski/gain

Here are links to articles about it:

https://medium.com/better-programming/an-introduction-to-gain-part-1-writing-high-performance-tcp-application-df5f7253e54a
https://betterprogramming.pub/gain-the-new-fastest-go-tcp-framework-40ec111d40e6

**Comment by espoal** [comment]
Sure @pawelgaczynski , would you like to open a PR?

**Comment by pawelgaczynski** [comment]
Sure: https://github.com/espoal/awesome-iouring/pull/12
