### ISSUE TITLE
Java / Android Libraries

### ISSUE THREAD

**Issue by threeseed** [espoal/awesome-iouring#6]
Java:

* https://github.com/ikorennoy/jasyncfio
* https://github.com/bbeaupain/nio_uring

Android:
* https://github.com/ikorennoy/kuring

**Comment by espoal** [comment]
Thanks for sharing, I added them to the lit. Next time feel free to open a PR :)

Question though: Are you sure kuring is for Android? I see no mention of it in the repo.

**Comment by threeseed** [comment]
For sure will do. 

io_uring is supported in Android and just assumed since it was Kotlin it was targeting Android. Maybe they all just belong in Java ?

**Comment by espoal** [comment]
it seems it doesn't, but work is undergoing to bring `io_uring` to android
